# Use the official Nginx base image
FROM nginx:latest

# Install OpenSSL to generate a self-signed SSL certificate
RUN apt-get update && apt-get install -y openssl

# Install Git (and any dependencies)
RUN apt-get install -y git
# Create necessary directories for SSL certificates and static files
RUN mkdir -p /etc/ssl/private /etc/ssl/certs

WORKDIR /app/nginx

COPY ./statuspage/statuspage/statuspage/static/ /app/nginx/static

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose ports 80 and 443 for HTTP and HTTPS traffic
EXPOSE 80

# Start Nginx in the foreground to keep the container running
CMD ["nginx", "-g", "daemon off;"]
~
~
