# Use the official Nginx base image
FROM nginx:latest

# Install OpenSSL to generate a self-signed SSL certificate
RUN apt-get update && apt-get install -y openssl

# Install Git (and any dependencies)
RUN apt-get install -y git
# Create necessary directories for SSL certificates and static files
RUN mkdir -p /etc/ssl/private /etc/ssl/certs

WORKDIR /app/nginx

COPY ./statuspage/statuspage/statuspage/static/ /app/nginx/static

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Generate a self-signed SSL certificate for HTTPS
# Modify the subject to match your domain (status-page.example.com)
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/status-page.key \
    -out /etc/ssl/certs/status-page.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=statuspage-bop.yoram-izilov.com"

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/prometheus.key \
    -out /etc/ssl/certs/prometheus.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=prometheus-bop.yoram-izilov.com"

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/grafana.key \
    -out /etc/ssl/certs/grafana.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=grafana-bop.yoram-izilov.com"

# Expose ports 80 and 443 for HTTP and HTTPS traffic
EXPOSE 80 443

# Start Nginx in the foreground to keep the container running
CMD ["nginx", "-g", "daemon off;"]
