apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: efklog
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-arn: arn:aws:elasticloadbalancing:us-east-1:992382545251:loadbalancer/classic/ae964f707a0a6409bbd4df27d170b50b

  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging
  type: LoadBalancer
