apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: efklog
  labels:
    k8s-app: kibana-logging
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601  # או מה שהגדרת בפוד
  selector:
    k8s-app: kibana-logging
  type: NodePort

