apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage
spec:
  replicas: 2  # Change to 2 replicas for rolling updates
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: statuspage
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-bop:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate  # Set to RollingUpdate for seamless updates
    rollingUpdate:
      maxUnavailable: 1  # Allow 1 pod to be unavailable during the update
      maxSurge: 1  # Allow 1 additional pod during the update
