apiVersion: v1
kind: Service
metadata:
  name: statuspage-service
spec:
  type: NodePort
  selector:
    app: statuspage  # Replace with your app label
  ports:
    - port: 8001         # Port that the service listens on
      targetPort: 8001   # Port on the pod to forward to
      nodePort: 30001    # Port to expose on each Node (optional; Kubernetes will assign one if not specified)

