apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      containers:
      - name: statuspage
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-bop:1.0.1
        ports:
        - containerPort: 8001
        imagePullPolicy: Always

